mutation createTodo(
    $input: CreateTodoInput!
){
    createTodo(input:$input){
        id , title
    }
}

query getAllTodos {
    todos (options: {paginate: {page: 1,limit: 10}}) {
        data{
            title ,
            id
        }
    }
}
